"""initial_schema

Revision ID: 773863f5a6aa
Revises:
Create Date: 2026-08-31 18:19:35.404501
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "773863f5a6aa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress_current", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','retry_wait','succeeded','failed','cancelled')", name="ck_job_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_background_jobs_available_at"), ["available_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_background_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_background_jobs_heartbeat_at"), ["heartbeat_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_background_jobs_lease_expires_at"), ["lease_expires_at"], unique=False)
        batch_op.create_index("ix_jobs_queue", ["status", "priority", "created_at"], unique=False)

    op.create_table(
        "libraries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("library_type", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_successful_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("library_type IN ('movies','tv','other')", name="ck_library_type"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.create_index("ix_libraries_enabled", ["enabled"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("normalized_username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_normalized_username"), ["normalized_username"], unique=True)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_created", ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False)

    op.create_table(
        "background_job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["background_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_job_events", schema=None) as batch_op:
        batch_op.create_index("ix_job_event_job_created", ["job_id", "created_at"], unique=False)

    op.create_table(
        "library_paths",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_path", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "canonical_path", name="uq_library_path"),
    )
    with op.batch_alter_table("library_paths", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_library_paths_library_id"), ["library_id"], unique=False)

    op.create_table(
        "media_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('movie','series','episode','other')", name="ck_media_kind"),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_items_library_id"), ["library_id"], unique=False)
        batch_op.create_index(
            "ix_media_library_available_title", ["library_id", "available", "sort_title"], unique=False
        )

    op.create_table(
        "scan_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("scan_mode", sa.String(length=16), nullable=False),
        sa.Column("discovered_files", sa.Integer(), nullable=False),
        sa.Column("processed_files", sa.Integer(), nullable=False),
        sa.Column("unchanged_files", sa.Integer(), nullable=False),
        sa.Column("missing_files", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["background_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_jobs_library_id"), ["library_id"], unique=False)

    op.create_table(
        "scan_locks",
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["background_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("library_id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_sessions_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "external_metadata_identifiers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_provider_external_id"),
    )
    with op.batch_alter_table("external_metadata_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_metadata_identifiers_media_item_id"), ["media_item_id"], unique=False
        )

    op.create_table(
        "local_artwork",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.Column("library_path_id", sa.String(length=36), nullable=False),
        sa.Column("artwork_type", sa.String(length=32), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("cached_path", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["library_path_id"], ["library_paths.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_item_id", "library_path_id", "artwork_type", "source_path", name="uq_artwork"),
    )
    with op.batch_alter_table("local_artwork", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_local_artwork_library_path_id"), ["library_path_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_local_artwork_media_item_id"), ["media_item_id"], unique=False)

    op.create_table(
        "media_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.Column("library_path_id", sa.String(length=36), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("modified_ns", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_scan_id", sa.String(length=36), nullable=True),
        sa.Column("container", sa.String(length=120), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("embedded_title", sa.String(length=500), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("analysis_duration_ms", sa.Integer(), nullable=True),
        sa.Column("analysis_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["library_path_id"], ["library_paths.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_path_id", "relative_path", name="uq_media_file_path"),
    )
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.create_index("ix_media_file_available_seen", ["available", "last_seen_scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_files_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_files_last_seen_scan_id"), ["last_seen_scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_files_library_path_id"), ["library_path_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_files_media_item_id"), ["media_item_id"], unique=False)

    op.create_table(
        "movies",
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("media_item_id"),
    )
    op.create_table(
        "series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_item_id"),
    )
    op.create_table(
        "audio_streams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_file_id", sa.String(length=36), nullable=False),
        sa.Column("stream_index", sa.Integer(), nullable=False),
        sa.Column("codec", sa.String(length=80), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("channel_layout", sa.String(length=80), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["media_file_id"], ["media_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_file_id", "stream_index", name="uq_audio_stream"),
    )
    with op.batch_alter_table("audio_streams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audio_streams_media_file_id"), ["media_file_id"], unique=False)

    op.create_table(
        "seasons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["series_id"], ["series.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "season_number", name="uq_series_season"),
    )
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seasons_series_id"), ["series_id"], unique=False)

    op.create_table(
        "subtitle_streams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_file_id", sa.String(length=36), nullable=False),
        sa.Column("stream_index", sa.Integer(), nullable=False),
        sa.Column("codec", sa.String(length=80), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hearing_impaired", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["media_file_id"], ["media_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_file_id", "stream_index", name="uq_subtitle_stream"),
    )
    with op.batch_alter_table("subtitle_streams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subtitle_streams_media_file_id"), ["media_file_id"], unique=False)

    op.create_table(
        "video_streams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_file_id", sa.String(length=36), nullable=False),
        sa.Column("stream_index", sa.Integer(), nullable=False),
        sa.Column("codec", sa.String(length=80), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["media_file_id"], ["media_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_file_id", "stream_index", name="uq_video_stream"),
    )
    with op.batch_alter_table("video_streams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_video_streams_media_file_id"), ["media_file_id"], unique=False)

    op.create_table(
        "episodes",
        sa.Column("media_item_id", sa.String(length=36), nullable=False),
        sa.Column("season_id", sa.String(length=36), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("part_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("media_item_id"),
        sa.UniqueConstraint("season_id", "episode_number", "part_number", name="uq_season_episode"),
    )
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_episodes_season_id"), ["season_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("episodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episodes_season_id"))

    op.drop_table("episodes")
    with op.batch_alter_table("video_streams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_streams_media_file_id"))

    op.drop_table("video_streams")
    with op.batch_alter_table("subtitle_streams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_streams_media_file_id"))

    op.drop_table("subtitle_streams")
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seasons_series_id"))

    op.drop_table("seasons")
    with op.batch_alter_table("audio_streams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_streams_media_file_id"))

    op.drop_table("audio_streams")
    op.drop_table("series")
    op.drop_table("movies")
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_files_media_item_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_library_path_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_last_seen_scan_id"))
        batch_op.drop_index(batch_op.f("ix_media_files_fingerprint"))
        batch_op.drop_index("ix_media_file_available_seen")

    op.drop_table("media_files")
    with op.batch_alter_table("local_artwork", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_local_artwork_library_path_id"))
        batch_op.drop_index(batch_op.f("ix_local_artwork_media_item_id"))

    op.drop_table("local_artwork")
    with op.batch_alter_table("external_metadata_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_metadata_identifiers_media_item_id"))

    op.drop_table("external_metadata_identifiers")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_expires_at"))

    op.drop_table("user_sessions")
    op.drop_table("user_roles")
    op.drop_table("scan_locks")
    with op.batch_alter_table("scan_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_jobs_library_id"))

    op.drop_table("scan_jobs")
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.drop_index("ix_media_library_available_title")
        batch_op.drop_index(batch_op.f("ix_media_items_library_id"))

    op.drop_table("media_items")
    with op.batch_alter_table("library_paths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_library_paths_library_id"))

    op.drop_table("library_paths")
    with op.batch_alter_table("background_job_events", schema=None) as batch_op:
        batch_op.drop_index("ix_job_event_job_created")

    op.drop_table("background_job_events")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))
        batch_op.drop_index("ix_audit_created")

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_normalized_username"))

    op.drop_table("users")
    op.drop_table("roles")
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_index("ix_libraries_enabled")

    op.drop_table("libraries")
    with op.batch_alter_table("background_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_queue")
        batch_op.drop_index(batch_op.f("ix_background_jobs_lease_expires_at"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_heartbeat_at"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_created_at"))
        batch_op.drop_index(batch_op.f("ix_background_jobs_available_at"))

    op.drop_table("background_jobs")
    op.drop_table("application_settings")
    # ### end Alembic commands ###
