[CmdletBinding()]
param(
    [Alias("MediaRoot")]
    [string[]]$MediaPath,
    [string[]]$MediaLabel,
    [switch]$ConfigureMediaRoots,
    [switch]$SkipMediaRoots,
    [switch]$NoBuild,
    [switch]$NoStart
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$EnvironmentFile = Join-Path $RepositoryRoot ".env"
$EnvironmentExample = Join-Path $RepositoryRoot ".env.example"
$ComposeFile = Join-Path $RepositoryRoot "compose.yml"
$ProductConfigFile = Join-Path $RepositoryRoot "config\product.json"
$LocalConfigurationDirectory = Join-Path $RepositoryRoot ".bluereel"
$MediaRootRegistryFile = Join-Path $LocalConfigurationDirectory "media-roots.tsv"
$ComposeOverrideFile = Join-Path $RepositoryRoot "compose.override.yml"
$MediaRootRegistryHeader = "# BlueReel approved media roots v1"
$GeneratedOverrideMarker = "# Generated by BlueReel bootstrap. Local machine only."

function Stop-WithMessage([string]$Message) {
    [Console]::Error.WriteLine("Error: $Message")
    exit 1
}

function New-SecureHexSecret {
    $bytes = New-Object byte[] 48
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    } finally {
        $generator.Dispose()
    }
    return [System.BitConverter]::ToString($bytes).Replace("-", "").ToLowerInvariant()
}

function New-StableMediaRootId {
    $bytes = New-Object byte[] 8
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    } finally {
        $generator.Dispose()
    }
    return "root_" + [System.BitConverter]::ToString($bytes).Replace("-", "").ToLowerInvariant()
}

function ConvertTo-DotEnvLiteral([string]$Value) {
    if ($Value -match '[\x00-\x1f\x7f]') {
        throw "A local configuration value contains an unsupported control character."
    }
    return "'" + $Value.Replace("'", "\'") + "'"
}

function Test-InteractiveInput {
    if (-not [Environment]::UserInteractive) { return $false }
    try { return -not [Console]::IsInputRedirected } catch { return $false }
}

function Select-NativeMediaFolder {
    if (-not (Test-InteractiveInput) -or $env:OS -ne "Windows_NT") { return $null }
    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
        $dialog = [System.Windows.Forms.FolderBrowserDialog]::new()
        try {
            $dialog.Description = "Choose a folder BlueReel may read as source media"
            if ($dialog.PSObject.Properties.Name -contains "UseDescriptionForTitle") {
                $dialog.UseDescriptionForTitle = $true
            }
            if ($dialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
                return $dialog.SelectedPath
            }
        } finally {
            $dialog.Dispose()
        }
    } catch {
        Write-Warning "A native folder dialog is unavailable in this PowerShell host; use typed-path selection instead."
    }
    return $null
}

function Read-InteractiveMediaRoots {
    $selected = [System.Collections.Generic.List[object]]::new()
    while ($true) {
        $choice = (Read-Host "Choose an approved media root: [B]rowse, [T]ype a path, or [S]kip").Trim().ToUpperInvariant()
        if ($choice -eq "S") { break }
        $path = $null
        if ($choice -eq "B") {
            $path = Select-NativeMediaFolder
            if (-not $path) {
                Write-Host "No folder was selected."
                continue
            }
        } elseif ($choice -eq "T") {
            $path = (Read-Host "Host folder path").Trim()
            if (-not $path) { continue }
        } else {
            Write-Host "Enter B, T, or S."
            continue
        }
        $label = (Read-Host "Friendly display name (press Enter to use the folder name)").Trim()
        $selected.Add([pscustomobject]@{ Path = $path; Label = $label })
        $more = (Read-Host "Add another approved media root? [y/N]").Trim()
        if ($more -notmatch '^(?i:y|yes)$') { break }
    }
    return @($selected)
}

function Resolve-SelectedMediaRoot([string]$Path, [string]$Label) {
    if ([string]::IsNullOrWhiteSpace($Path) -or $Path -match '[\x00-\x1f\x7f]') {
        throw "A selected media path is empty or contains an unsupported control character."
    }
    if ($Path.Contains('$')) {
        throw "Media paths containing a dollar sign are unsupported because Docker Compose interpolates that character. Select a dedicated wrapper folder without a dollar sign."
    }
    $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
    if (-not $item.PSIsContainer) { throw "The selected media path is not a directory: $Path" }
    if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
        throw "The selected media root is a link or reparse point. Select its real directory instead: $Path"
    }
    $resolved = [System.IO.Path]::GetFullPath($item.FullName).TrimEnd('\', '/')
    $root = [System.IO.Path]::GetPathRoot($item.FullName).TrimEnd('\', '/')
    if ($resolved.Equals($root, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "A whole drive or filesystem root is too broad. Select a dedicated media directory instead: $Path"
    }
    try {
        $enumerator = [System.IO.Directory]::EnumerateFileSystemEntries($resolved).GetEnumerator()
        try { $null = $enumerator.MoveNext() } finally { if ($enumerator -is [System.IDisposable]) { $enumerator.Dispose() } }
    } catch {
        throw "The selected media directory is not readable: $Path"
    }
    $labelWasExplicit = -not [string]::IsNullOrWhiteSpace($Label)
    $displayName = $Label.Trim()
    if (-not $displayName) { $displayName = Split-Path -Leaf $resolved }
    if (-not $displayName) { $displayName = "Media" }
    if ($displayName.Length -gt 80 -or $displayName -match '[\x00-\x1f\x7f]') {
        throw "A media-root display name must be 1-80 printable characters."
    }
    if ($displayName.Contains('$')) {
        throw "Media-root display names cannot contain a dollar sign because Docker Compose interpolates that character."
    }
    return [pscustomobject]@{
        HostPath = $resolved.Replace('\', '/')
        DisplayName = $displayName
        LabelWasExplicit = $labelWasExplicit
    }
}

function Read-MediaRootRegistry {
    if (-not (Test-Path -LiteralPath $MediaRootRegistryFile -PathType Leaf)) { return @() }
    $lines = [System.IO.File]::ReadAllLines($MediaRootRegistryFile)
    if ($lines.Count -eq 0 -or $lines[0] -ne $MediaRootRegistryHeader) {
        throw "The local media-root registry is not managed by this bootstrap script: $MediaRootRegistryFile"
    }
    $roots = [System.Collections.Generic.List[object]]::new()
    $ids = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    $targets = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($line in $lines | Select-Object -Skip 1) {
        if (-not $line) { continue }
        $fields = $line.Split("`t", 4)
        $expectedTarget = if ($roots.Count -eq 0) { "/media" } else { "/media-roots/$($fields[0])" }
        if ($fields.Count -ne 4 -or $fields[0] -notmatch '^[a-z0-9][a-z0-9_-]{0,63}$' -or
            ($roots.Count -eq 0 -and $fields[0] -ne "primary") -or
            ($roots.Count -gt 0 -and $fields[0] -eq "primary") -or
            $fields[2] -ne $expectedTarget -or [string]::IsNullOrWhiteSpace($fields[1]) -or
            [string]::IsNullOrWhiteSpace($fields[3]) -or -not $ids.Add($fields[0]) -or -not $targets.Add($fields[2])) {
            throw "The local media-root registry is invalid: $MediaRootRegistryFile"
        }
        $roots.Add([pscustomobject]@{
            Id = $fields[0]
            DisplayName = $fields[1]
            ContainerPath = $fields[2]
            HostPath = $fields[3]
        })
    }
    return @($roots)
}

function Test-ManagedComposeOverride {
    if (-not (Test-Path -LiteralPath $ComposeOverrideFile -PathType Leaf)) { return $false }
    return (Get-Content -LiteralPath $ComposeOverrideFile -TotalCount 1) -eq $GeneratedOverrideMarker
}

function Update-DotEnvContent([string]$Content, [System.Collections.IDictionary]$Updates) {
    $newline = if ($Content.Contains("`r`n")) { "`r`n" } else { "`n" }
    foreach ($key in $Updates.Keys) {
        $replacement = "$key=$($Updates[$key])"
        $pattern = "(?m)^" + [regex]::Escape($key) + "=.*$"
        if ([regex]::IsMatch($Content, $pattern)) {
            $Content = [regex]::Replace($Content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $replacement })
        } else {
            if ($Content.Length -gt 0 -and -not $Content.EndsWith("`n")) { $Content += $newline }
            $Content += $replacement + $newline
        }
    }
    return $Content
}

function Write-AtomicUtf8([string]$Path, [string]$Content) {
    $directory = Split-Path -Parent $Path
    [System.IO.Directory]::CreateDirectory($directory) | Out-Null
    $temporary = Join-Path $directory ("." + [System.IO.Path]::GetFileName($Path) + ".tmp." + [guid]::NewGuid().ToString("N"))
    try {
        [System.IO.File]::WriteAllText($temporary, $Content, [System.Text.UTF8Encoding]::new($false))
        Move-Item -LiteralPath $temporary -Destination $Path -Force
    } finally {
        if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
    }
}

function Read-DotEnv([string]$Path) {
    $values = @{}
    foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith("#")) { continue }
        $separator = $trimmed.IndexOf("=")
        if ($separator -lt 1) { continue }
        $key = $trimmed.Substring(0, $separator).Trim()
        $value = $trimmed.Substring($separator + 1).Trim()
        if ($value.StartsWith("'") -and $value.EndsWith("'")) {
            $value = $value.Substring(1, $value.Length - 2)
            $value = $value.Replace("\'", "'")
        } elseif ($value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $values[$key] = $value
    }
    return $values
}

function Resolve-ConfiguredPath([string]$Value) {
    if ([System.IO.Path]::IsPathRooted($Value)) {
        return [System.IO.Path]::GetFullPath($Value)
    }
    return [System.IO.Path]::GetFullPath((Join-Path $RepositoryRoot $Value))
}

function Set-MediaRootConfiguration([object[]]$Selections, [hashtable]$ResolvedState) {
    if ($Selections.Count -eq 0) { return $false }
    if ((Test-Path -LiteralPath $ComposeOverrideFile) -and -not (Test-ManagedComposeOverride)) {
        Stop-WithMessage "compose.override.yml already exists and is not managed by BlueReel. It was not overwritten; merge approved media roots deliberately."
    }

    try { $existing = @(Read-MediaRootRegistry) } catch { Stop-WithMessage $_.Exception.Message }
    $resolvedSelections = [System.Collections.Generic.List[object]]::new()
    foreach ($selection in $Selections) {
        try {
            $resolvedSelections.Add((Resolve-SelectedMediaRoot -Path $selection.Path -Label $selection.Label))
        } catch {
            Stop-WithMessage $_.Exception.Message
        }
    }
    $existingPrimary = $existing | Where-Object { $_.Id -eq "primary" } | Select-Object -First 1
    if ($existingPrimary) {
        for ($index = 1; $index -lt $resolvedSelections.Count; $index++) {
            if ($resolvedSelections[$index].HostPath.Equals(
                    $existingPrimary.HostPath,
                    [System.StringComparison]::OrdinalIgnoreCase
                )) {
                Stop-WithMessage "The registered primary media root must remain first so existing /media library paths stay stable. Omit it only for an explicit replacement."
            }
        }
    }
    for ($leftIndex = 0; $leftIndex -lt $resolvedSelections.Count; $leftIndex++) {
        $left = $resolvedSelections[$leftIndex].HostPath.TrimEnd('/')
        $leftPrefix = $left + "/"
        for ($rightIndex = $leftIndex + 1; $rightIndex -lt $resolvedSelections.Count; $rightIndex++) {
            $right = $resolvedSelections[$rightIndex].HostPath.TrimEnd('/')
            $rightPrefix = $right + "/"
            if ($left.Equals($right, [System.StringComparison]::OrdinalIgnoreCase) -or
                $left.StartsWith($rightPrefix, [System.StringComparison]::OrdinalIgnoreCase) -or
                $right.StartsWith($leftPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                Stop-WithMessage "Approved media roots must be distinct and cannot contain one another."
            }
        }
        foreach ($entry in $ResolvedState.GetEnumerator()) {
            $state = $entry.Value.Replace('\', '/').TrimEnd('/')
            $statePrefix = $state + "/"
            if ($left.Equals($state, [System.StringComparison]::OrdinalIgnoreCase) -or
                $left.StartsWith($statePrefix, [System.StringComparison]::OrdinalIgnoreCase) -or
                $state.StartsWith($leftPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
                Stop-WithMessage "$($entry.Key) and an approved media root overlap. Runtime writes must remain isolated from source media."
            }
        }
    }

    $records = [System.Collections.Generic.List[object]]::new()
    $usedIds = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    for ($index = 0; $index -lt $resolvedSelections.Count; $index++) {
        $selection = $resolvedSelections[$index]
        $prior = $existing | Where-Object { $_.HostPath.Equals($selection.HostPath, [System.StringComparison]::OrdinalIgnoreCase) } | Select-Object -First 1
        if ($index -eq 0) {
            $id = "primary"
            $containerPath = "/media"
        } elseif ($prior -and $prior.Id -ne "primary") {
            $id = $prior.Id
            $containerPath = $prior.ContainerPath
        } else {
            do { $id = New-StableMediaRootId } while ($usedIds.Contains($id))
            $containerPath = "/media-roots/$id"
        }
        $null = $usedIds.Add($id)
        $displayName = if ($selection.LabelWasExplicit) {
            $selection.DisplayName
        } elseif ($prior) {
            $prior.DisplayName
        } else {
            $selection.DisplayName
        }
        $records.Add([pscustomobject]@{
            Id = $id
            DisplayName = $displayName
            ContainerPath = $containerPath
            HostPath = $selection.HostPath
        })
    }

    $definitions = @($records | ForEach-Object {
        [ordered]@{ id = $_.Id; display_name = $_.DisplayName; path = $_.ContainerPath }
    })
    $definitionsJson = ConvertTo-Json -InputObject $definitions -Compress -Depth 4
    $rootPaths = ($records | ForEach-Object { $_.ContainerPath }) -join ":"
    $environmentContent = [System.IO.File]::ReadAllText($EnvironmentFile)
    $environmentContent = Update-DotEnvContent $environmentContent ([ordered]@{
        MEDIA_PATH = (ConvertTo-DotEnvLiteral $records[0].HostPath)
        MEDIA_ROOTS = $rootPaths
        MEDIA_ROOT_DEFINITIONS = (ConvertTo-DotEnvLiteral $definitionsJson)
    })

    $overrideContent = $null
    if ($records.Count -gt 1) {
        $mounts = @($records | Select-Object -Skip 1 | ForEach-Object {
            [ordered]@{ type = "bind"; source = $_.HostPath; target = $_.ContainerPath; read_only = $true }
        })
        $override = [ordered]@{
            "x-bluereel-generated" = [ordered]@{ version = 1; purpose = "approved read-only media roots" }
            services = [ordered]@{
                backend = [ordered]@{ volumes = $mounts }
                worker = [ordered]@{ volumes = $mounts }
            }
        }
        $overrideContent = $GeneratedOverrideMarker + "`n" + (ConvertTo-Json -InputObject $override -Depth 8) + "`n"
    }

    $candidateEnvironment = Join-Path $RepositoryRoot (".env.media-roots.tmp." + [guid]::NewGuid().ToString("N"))
    $candidateOverride = Join-Path $RepositoryRoot ("compose.media-roots.tmp." + [guid]::NewGuid().ToString("N") + ".yml")
    try {
        [System.IO.File]::WriteAllText($candidateEnvironment, $environmentContent, [System.Text.UTF8Encoding]::new($false))
        $composeArguments = @("compose", "--env-file", $candidateEnvironment, "-f", $ComposeFile)
        if ($overrideContent) {
            [System.IO.File]::WriteAllText($candidateOverride, $overrideContent, [System.Text.UTF8Encoding]::new($false))
            $composeArguments += @("-f", $candidateOverride)
        }
        $composeArguments += @("config", "--quiet")
        & docker @composeArguments
        if ($LASTEXITCODE -ne 0) {
            Stop-WithMessage "Docker Compose rejected the proposed media-root configuration; existing local configuration was not changed."
        }
    } finally {
        if (Test-Path -LiteralPath $candidateEnvironment) { Remove-Item -LiteralPath $candidateEnvironment -Force }
        if (Test-Path -LiteralPath $candidateOverride) { Remove-Item -LiteralPath $candidateOverride -Force }
    }

    $registryLines = [System.Collections.Generic.List[string]]::new()
    $registryLines.Add($MediaRootRegistryHeader)
    foreach ($record in $records) {
        $registryLines.Add(($record.Id, $record.DisplayName, $record.ContainerPath, $record.HostPath) -join "`t")
    }
    Write-AtomicUtf8 $EnvironmentFile $environmentContent
    Write-AtomicUtf8 $MediaRootRegistryFile (($registryLines -join "`n") + "`n")
    if ($overrideContent) {
        Write-AtomicUtf8 $ComposeOverrideFile $overrideContent
    } elseif (Test-ManagedComposeOverride) {
        Remove-Item -LiteralPath $ComposeOverrideFile -Force
    }
    Write-Host "Approved media roots were configured. Adding or changing roots requires controlled container recreation."
    foreach ($record in $records) {
        Write-Host ("  {0}: {1} -> {2} (read-only)" -f $record.DisplayName, $record.HostPath, $record.ContainerPath)
    }
    return $true
}

function Test-PrivateBindAddress([string]$Address) {
    $parsed = $null
    if (-not [System.Net.IPAddress]::TryParse($Address, [ref]$parsed)) { return $false }
    if ([System.Net.IPAddress]::IsLoopback($parsed)) { return $true }
    if ($parsed.AddressFamily -ne [System.Net.Sockets.AddressFamily]::InterNetwork) { return $false }
    $octets = $parsed.GetAddressBytes()
    return ($octets[0] -eq 10) -or
        ($octets[0] -eq 172 -and $octets[1] -ge 16 -and $octets[1] -le 31) -or
        ($octets[0] -eq 192 -and $octets[1] -eq 168)
}

if (-not (Test-Path -LiteralPath $ComposeFile -PathType Leaf)) {
    Stop-WithMessage "compose.yml was not found at $ComposeFile. Run this script from a complete application checkout."
}
if (-not (Test-Path -LiteralPath $ProductConfigFile -PathType Leaf)) {
    Stop-WithMessage "Central product configuration is missing: $ProductConfigFile"
}
try {
    $productConfiguration = Get-Content -LiteralPath $ProductConfigFile -Raw | ConvertFrom-Json
    $ProductName = [string]$productConfiguration.name
} catch {
    Stop-WithMessage "Central product configuration is not valid JSON: $ProductConfigFile"
}
if ([string]::IsNullOrWhiteSpace($ProductName)) {
    Stop-WithMessage "Central product configuration must define a non-empty name."
}

$SuppliedMediaPaths = [System.Collections.Generic.List[string]]::new()
foreach ($value in @($MediaPath)) {
    if (-not [string]::IsNullOrWhiteSpace($value)) { $SuppliedMediaPaths.Add($value) }
}
$SuppliedMediaLabels = [System.Collections.Generic.List[string]]::new()
foreach ($value in @($MediaLabel)) {
    if ($null -ne $value) { $SuppliedMediaLabels.Add($value) }
}
if ($SkipMediaRoots -and ($ConfigureMediaRoots -or $SuppliedMediaPaths.Count -gt 0)) {
    Stop-WithMessage "-SkipMediaRoots cannot be combined with -ConfigureMediaRoots or -MediaPath."
}
if ($SuppliedMediaLabels.Count -gt $SuppliedMediaPaths.Count) {
    Stop-WithMessage "Each -MediaLabel value must correspond to a supplied -MediaPath."
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Stop-WithMessage @"
Docker is not installed or is not on PATH. Install Docker Desktop, enable its WSL 2 engine when supported, start Docker Desktop, and rerun this script.
One installation option is: winget install --exact --id Docker.DockerDesktop
No packages or system settings were changed.
"@
}

& docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) {
    Stop-WithMessage "Docker Compose v2 is unavailable. Update Docker Desktop so 'docker compose' works, then rerun this script."
}

& docker info | Out-Null
if ($LASTEXITCODE -ne 0) {
    Stop-WithMessage "The Docker engine is not reachable. Start Docker Desktop and wait until it reports that the engine is running."
}

if (Get-Command wsl.exe -ErrorAction SilentlyContinue) {
    & wsl.exe --status | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "WSL 2 status could not be read. Docker Desktop can explain whether its WSL 2 backend needs attention."
    }
} else {
    Write-Warning "WSL is not installed. Docker Desktop may use another supported backend; install WSL 2 if Docker Desktop requests it."
}

$createdEnvironment = $false
if (Test-Path -LiteralPath $EnvironmentFile) {
    Write-Host "Keeping existing .env; it was not overwritten."
    if ($SuppliedMediaPaths.Count -gt 0 -and -not $ConfigureMediaRoots) {
        Stop-WithMessage "Existing media-root configuration was not changed. Rerun with -ConfigureMediaRoots and the intended -MediaPath values."
    }
} else {
    if (-not (Test-Path -LiteralPath $EnvironmentExample -PathType Leaf)) {
        Stop-WithMessage ".env.example is missing; refusing to invent an incomplete configuration."
    }
    $contents = [System.IO.File]::ReadAllText($EnvironmentExample)
    $secret = New-SecureHexSecret
    $contents = $contents -replace 'APP_SECRET_KEY=GENERATE_WITH_BOOTSTRAP_DO_NOT_USE', "APP_SECRET_KEY=$secret"
    [System.IO.File]::WriteAllText($EnvironmentFile, $contents, [System.Text.UTF8Encoding]::new($false))
    $createdEnvironment = $true
    Write-Host "Created .env with a cryptographically secure application secret."
}

$settings = Read-DotEnv $EnvironmentFile
$requiredKeys = @(
    "APP_SECRET_KEY", "BIND_ADDRESS", "HTTP_PORT", "DATA_PATH", "DATABASE_PATH",
    "ARTWORK_PATH", "TEMP_PATH", "MEDIA_PATH", "BACKUP_PATH", "PUID", "PGID"
)
foreach ($key in $requiredKeys) {
    if (-not $settings.ContainsKey($key) -or [string]::IsNullOrWhiteSpace($settings[$key])) {
        Stop-WithMessage ".env is missing required setting $key. Compare it with .env.example; the script did not overwrite it."
    }
}

if ($settings["APP_SECRET_KEY"] -eq "GENERATE_WITH_BOOTSTRAP_DO_NOT_USE" -or $settings["APP_SECRET_KEY"].Length -lt 64) {
    Stop-WithMessage "APP_SECRET_KEY is still a placeholder or is too short. Move the existing .env aside and rerun bootstrap, or set a cryptographically random value of at least 64 characters."
}
if (-not (Test-PrivateBindAddress $settings["BIND_ADDRESS"])) {
    Stop-WithMessage "BIND_ADDRESS must be a loopback or RFC1918 private IPv4 address. Public and wildcard binds are intentionally rejected."
}
$port = 0
if (-not [int]::TryParse($settings["HTTP_PORT"], [ref]$port) -or $port -lt 1 -or $port -gt 65535) {
    Stop-WithMessage "HTTP_PORT must be an integer from 1 through 65535."
}
foreach ($identityKey in @("PUID", "PGID")) {
    $identity = 0
    if (-not [int]::TryParse($settings[$identityKey], [ref]$identity) -or $identity -lt 1) {
        Stop-WithMessage "$identityKey must be a positive numeric container identity; running application containers as root is rejected."
    }
}

$stateKeys = @("DATA_PATH", "DATABASE_PATH", "ARTWORK_PATH", "TEMP_PATH", "BACKUP_PATH")
$resolvedState = @{}
foreach ($key in $stateKeys) {
    $resolved = Resolve-ConfiguredPath $settings[$key]
    if ($resolved -eq [System.IO.Path]::GetPathRoot($resolved) -or $resolved -eq $RepositoryRoot) {
        Stop-WithMessage "$key resolves to an unsafe broad directory: $resolved"
    }
    [System.IO.Directory]::CreateDirectory($resolved) | Out-Null
    $probe = Join-Path $resolved (".application-write-test-" + [guid]::NewGuid().ToString("N"))
    try {
        [System.IO.File]::WriteAllText($probe, "test")
    } finally {
        if (Test-Path -LiteralPath $probe) { Remove-Item -LiteralPath $probe -Force }
    }
    $resolvedState[$key] = $resolved.TrimEnd('\', '/')
}

for ($leftIndex = 0; $leftIndex -lt $stateKeys.Count; $leftIndex++) {
    $leftKey = $stateKeys[$leftIndex]
    $leftPath = $resolvedState[$leftKey]
    $leftPrefix = $leftPath + [System.IO.Path]::DirectorySeparatorChar
    for ($rightIndex = $leftIndex + 1; $rightIndex -lt $stateKeys.Count; $rightIndex++) {
        $rightKey = $stateKeys[$rightIndex]
        $rightPath = $resolvedState[$rightKey]
        $rightPrefix = $rightPath + [System.IO.Path]::DirectorySeparatorChar
        if ($leftPath -eq $rightPath -or
            $leftPath.StartsWith($rightPrefix, [System.StringComparison]::OrdinalIgnoreCase) -or
            $rightPath.StartsWith($leftPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            Stop-WithMessage "$leftKey and $rightKey overlap. Application state paths must be isolated, not equal or nested."
        }
    }
}

$requestedMediaRoots = [System.Collections.Generic.List[object]]::new()
for ($index = 0; $index -lt $SuppliedMediaPaths.Count; $index++) {
    $label = if ($index -lt $SuppliedMediaLabels.Count) { $SuppliedMediaLabels[$index] } else { "" }
    $requestedMediaRoots.Add([pscustomobject]@{ Path = $SuppliedMediaPaths[$index]; Label = $label })
}
if ($requestedMediaRoots.Count -eq 0 -and -not $SkipMediaRoots -and ($createdEnvironment -or $ConfigureMediaRoots)) {
    if (Test-InteractiveInput) {
        Write-Host "Choose one or more host folders BlueReel may read. You may skip and configure them later."
        foreach ($selection in @(Read-InteractiveMediaRoots)) { $requestedMediaRoots.Add($selection) }
    } elseif ($ConfigureMediaRoots) {
        Stop-WithMessage "No media roots were supplied in a non-interactive session. Pass -MediaPath or omit -ConfigureMediaRoots."
    }
}
$mediaConfigurationChanged = $false
if ($requestedMediaRoots.Count -gt 0) {
    $mediaConfigurationChanged = Set-MediaRootConfiguration -Selections @($requestedMediaRoots) -ResolvedState $resolvedState
    $settings = Read-DotEnv $EnvironmentFile
}

$resolvedMediaPath = Resolve-ConfiguredPath $settings["MEDIA_PATH"]
if (-not (Test-Path -LiteralPath $resolvedMediaPath -PathType Container)) {
    if ($createdEnvironment -and $settings["MEDIA_PATH"] -eq "./media") {
        [System.IO.Directory]::CreateDirectory($resolvedMediaPath) | Out-Null
        Write-Host "Created the default empty media directory at $resolvedMediaPath."
    } else {
        Stop-WithMessage "MEDIA_PATH does not exist or is not a directory: $resolvedMediaPath"
    }
}
try { Get-ChildItem -LiteralPath $resolvedMediaPath -Force -ErrorAction Stop | Select-Object -First 1 | Out-Null } catch {
    Stop-WithMessage "MEDIA_PATH is not readable by the current user: $resolvedMediaPath"
}

try { $registeredRoots = @(Read-MediaRootRegistry) } catch { Stop-WithMessage $_.Exception.Message }
if ($registeredRoots.Count -gt 1 -and -not (Test-ManagedComposeOverride)) {
    Stop-WithMessage "Multiple approved media roots are registered, but their managed Compose override is missing or unrecognized."
}
foreach ($root in $registeredRoots) {
    try { $validatedRoot = Resolve-SelectedMediaRoot -Path $root.HostPath -Label $root.DisplayName } catch { Stop-WithMessage $_.Exception.Message }
    $mediaHost = $validatedRoot.HostPath.TrimEnd('/')
    $mediaHostPrefix = $mediaHost + "/"
    foreach ($entry in $resolvedState.GetEnumerator()) {
        $stateHost = $entry.Value.Replace('\', '/').TrimEnd('/')
        $stateHostPrefix = $stateHost + "/"
        if ($mediaHost.Equals($stateHost, [System.StringComparison]::OrdinalIgnoreCase) -or
            $mediaHost.StartsWith($stateHostPrefix, [System.StringComparison]::OrdinalIgnoreCase) -or
            $stateHost.StartsWith($mediaHostPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            Stop-WithMessage "$($entry.Key) and a configured media root overlap. Runtime writes must remain isolated from source media."
        }
    }
}

$mediaPrefix = $resolvedMediaPath.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
foreach ($entry in $resolvedState.GetEnumerator()) {
    $statePrefix = $entry.Value + [System.IO.Path]::DirectorySeparatorChar
    if ($entry.Value -eq $resolvedMediaPath -or $entry.Value.StartsWith($mediaPrefix, [System.StringComparison]::OrdinalIgnoreCase) -or
        $resolvedMediaPath.StartsWith($statePrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        Stop-WithMessage "$($entry.Key) and MEDIA_PATH overlap. Runtime writes must be isolated from read-only source media."
    }
}

Push-Location $RepositoryRoot
try {
    docker compose --env-file $EnvironmentFile config --quiet
    if ($LASTEXITCODE -ne 0) { Stop-WithMessage "Docker Compose rejected the generated configuration; no services were started." }
    if ($NoStart) {
        $recreationNote = if ($mediaConfigurationChanged) { " Re-run without -NoStart to recreate the affected containers safely." } else { "" }
        Write-Host "Configuration and paths are valid. Services were not started because -NoStart was supplied.$recreationNote"
        return
    }

    $upArguments = @("compose", "--env-file", $EnvironmentFile, "up", "--detach")
    if (-not $NoBuild) { $upArguments += "--build" }
    & docker @upArguments
    if ($LASTEXITCODE -ne 0) { Stop-WithMessage "Docker Compose could not start $ProductName. Run 'docker compose logs' for details." }
} finally {
    Pop-Location
}

$address = $settings["BIND_ADDRESS"]
$displayHost = if ($address -eq "127.0.0.1" -or $address -eq "::1") { "localhost" } else { $address }
$localUrl = "http://${displayHost}:$port"
$healthUrl = "$localUrl/api/v1/health/ready"
$healthy = $false
for ($attempt = 1; $attempt -le 60; $attempt++) {
    try {
        $response = Invoke-WebRequest -Uri $healthUrl -Method Get -TimeoutSec 3 -UseBasicParsing
        if ($response.StatusCode -eq 200) { $healthy = $true; break }
    } catch {
        Start-Sleep -Seconds 2
    }
}
if (-not $healthy) {
    Stop-WithMessage "Services started but readiness did not succeed within 120 seconds. Inspect with: docker compose logs"
}

Write-Host "$ProductName is ready at $localUrl"
Write-Host "Complete Owner setup in the browser. No public firewall or router settings were changed."
