#!/usr/bin/env sh
set -eu

umask 077

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
ENVIRONMENT_FILE="$REPOSITORY_ROOT/.env"
ENVIRONMENT_EXAMPLE="$REPOSITORY_ROOT/.env.example"
COMPOSE_FILE="$REPOSITORY_ROOT/compose.yml"
PRODUCT_CONFIG_FILE="$REPOSITORY_ROOT/config/product.json"
NO_BUILD=0
NO_START=0
CONFIGURE_MEDIA_ROOTS=0
SKIP_MEDIA_ROOTS=0
MEDIA_OVERRIDES=""
LOCAL_CONFIGURATION_DIRECTORY="$REPOSITORY_ROOT/.bluereel"
MEDIA_ROOT_REGISTRY_FILE="$LOCAL_CONFIGURATION_DIRECTORY/media-roots.tsv"
COMPOSE_OVERRIDE_FILE="$REPOSITORY_ROOT/compose.override.yml"
MEDIA_ROOT_REGISTRY_HEADER="# BlueReel approved media roots v1"
GENERATED_OVERRIDE_MARKER="# Generated by BlueReel bootstrap. Local machine only."
TAB=$(printf '\t')

usage() {
  printf '%s\n' "Usage: $0 [--configure-media-roots] [--media-path DIRECTORY ...] [--skip-media-roots] [--no-build] [--no-start]"
}

fail() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --media-path)
      [ "$#" -ge 2 ] || fail "--media-path requires a directory."
      case "$2" in *"$TAB"*|*'
'*) fail "Media paths cannot contain tabs or newlines.";; esac
      MEDIA_OVERRIDES="${MEDIA_OVERRIDES}${MEDIA_OVERRIDES:+
}$2"
      shift 2
      ;;
    --configure-media-roots)
      CONFIGURE_MEDIA_ROOTS=1
      shift
      ;;
    --skip-media-roots)
      SKIP_MEDIA_ROOTS=1
      shift
      ;;
    --no-build)
      NO_BUILD=1
      shift
      ;;
    --no-start)
      NO_START=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      fail "Unknown option: $1"
      ;;
  esac
done

[ "$SKIP_MEDIA_ROOTS" -eq 0 ] || {
  [ "$CONFIGURE_MEDIA_ROOTS" -eq 0 ] && [ -z "$MEDIA_OVERRIDES" ] ||
    fail "--skip-media-roots cannot be combined with --configure-media-roots or --media-path."
}

[ -f "$COMPOSE_FILE" ] || fail "compose.yml was not found at $COMPOSE_FILE. Run this script from a complete application checkout."
[ -f "$PRODUCT_CONFIG_FILE" ] || fail "Central product configuration is missing: $PRODUCT_CONFIG_FILE"
PRODUCT_NAME=$(awk -F'"' '$2 == "name" { print $4; exit }' "$PRODUCT_CONFIG_FILE")
[ -n "$PRODUCT_NAME" ] || fail "Central product configuration must define a non-empty JSON name."

if ! command -v docker >/dev/null 2>&1; then
  cat >&2 <<'EOF'
Docker is not installed or is not on PATH. Install Docker Engine from Docker's
official repository plus the Docker Compose plugin, start the service, add your
user to the docker group if appropriate for your security policy, then rerun.
No packages, firewall rules, or services were changed by this script.
EOF
  exit 1
fi

docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is unavailable. Install the docker-compose-plugin package and rerun."
docker info >/dev/null 2>&1 || fail "The Docker engine is not reachable. Start it, or correct this user's Docker socket permissions, then rerun."
[ "$(id -u)" -ne 0 ] || fail "Run bootstrap as the intended unprivileged application owner, not root or through sudo."

generate_secret() {
  if [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
    od -An -N48 -tx1 /dev/urandom | tr -d ' \n'
  elif command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 48
  else
    fail "A secure random generator is unavailable (need /dev/urandom with od, or openssl)."
  fi
}

env_value() {
  awk -v wanted="$1" '
    /^[[:space:]]*#/ { next }
    {
      line=$0
      sub(/\r$/, "", line)
      pos=index(line, "=")
      if (pos == 0) next
      key=substr(line, 1, pos-1)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key == wanted) {
        value=substr(line, pos+1)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
        if (substr(value,1,1) == "\047" && substr(value,length(value),1) == "\047") {
          value=substr(value,2,length(value)-2)
          gsub(/\\\047/, "\047", value)
        } else if (substr(value,1,1) == "\"" && substr(value,length(value),1) == "\"") {
          value=substr(value,2,length(value)-2)
        }
        print value
        exit
      }
    }
  ' "$ENVIRONMENT_FILE"
}

replace_env_value() {
  key=$1
  value=$2
  target_file=${3:-$ENVIRONMENT_FILE}
  temp_file="$target_file.tmp.$$"
  BLUE_REEL_ENV_REPLACEMENT=$value awk -v wanted="$key" '
    BEGIN { replaced=0; replacement=ENVIRON["BLUE_REEL_ENV_REPLACEMENT"] }
    {
      line=$0
      pos=index(line, "=")
      key=(pos > 0 ? substr(line,1,pos-1) : "")
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      if (key == wanted) {
        print wanted "=" replacement
        replaced=1
      } else {
        print $0
      }
    }
    END { if (!replaced) print wanted "=" replacement }
  ' "$target_file" > "$temp_file"
  mv -- "$temp_file" "$target_file"
}

interactive_input_available() {
  [ -t 0 ] && [ -r /dev/tty ]
}

collect_interactive_media_roots() {
  while :; do
    printf '%s' "Configure an approved media folder: [T]ype a path or [S]kip: " >/dev/tty
    IFS= read -r choice </dev/tty || return
    case "$choice" in
      [Ss]|[Ss][Kk][Ii][Pp]) return ;;
      [Tt]|[Tt][Yy][Pp][Ee])
        printf '%s' "Host folder path: " >/dev/tty
        IFS= read -r selected </dev/tty || return
        [ -n "$selected" ] || continue
        case "$selected" in *"$TAB"*|*'
'*) fail "Media paths cannot contain tabs or newlines.";; esac
        MEDIA_OVERRIDES="${MEDIA_OVERRIDES}${MEDIA_OVERRIDES:+
}$selected"
        ;;
      *)
        printf '%s\n' "Enter T or S." >/dev/tty
        continue
        ;;
    esac
    printf '%s' "Add another approved media root? [y/N]: " >/dev/tty
    IFS= read -r more </dev/tty || return
    case "$more" in [Yy]|[Yy][Ee][Ss]) : ;; *) return ;; esac
  done
}

canonical_media_path() {
  selected=$1
  case "$selected" in *'$'*) fail "Media paths containing a dollar sign are unsupported because Docker Compose interpolates that character. Select a wrapper folder without a dollar sign.";; esac
  [ -d "$selected" ] || fail "The selected media directory does not exist: $selected"
  if printf '%s' "$selected" | LC_ALL=C grep '[[:cntrl:]]' >/dev/null 2>&1; then
    fail "The selected media path contains an unsupported control character."
  fi
  canonical=$(CDPATH= cd -- "$selected" && pwd -P) || fail "The selected media directory cannot be resolved: $selected"
  [ "$canonical" != / ] || fail "A whole filesystem root is too broad; select a dedicated media directory."
  [ -r "$canonical" ] && [ -x "$canonical" ] || fail "The selected media directory is not readable/traversable: $selected"
  [ ! -L "$selected" ] || fail "The selected media root is a symbolic link; select its real directory instead."
  printf '%s\n' "$canonical"
}

json_escape() {
  printf '%s' "$1" | awk '{ gsub(/\\/, "\\\\"); gsub(/\"/, "\\\""); printf "%s", $0 }'
}

dotenv_single_quote() {
  escaped=$(printf '%s' "$1" | sed "s/'/\\\\'/g")
  printf "'%s'" "$escaped"
}

yaml_single_quote() {
  printf '%s' "$1" | sed "s/'/''/g"
}

new_media_root_id() {
  printf 'root_%s\n' "$(od -An -N8 -tx1 /dev/urandom | tr -d ' \n')"
}

managed_compose_override() {
  [ -f "$COMPOSE_OVERRIDE_FILE" ] || return 1
  IFS= read -r first_line < "$COMPOSE_OVERRIDE_FILE" || return 1
  [ "$first_line" = "$GENERATED_OVERRIDE_MARKER" ]
}

validate_registry() {
  [ -f "$MEDIA_ROOT_REGISTRY_FILE" ] || return 0
  IFS= read -r first_line < "$MEDIA_ROOT_REGISTRY_FILE" || fail "The local media-root registry cannot be read."
  [ "$first_line" = "$MEDIA_ROOT_REGISTRY_HEADER" ] ||
    fail "The local media-root registry is not managed by this bootstrap script: $MEDIA_ROOT_REGISTRY_FILE"
}

configure_media_roots() {
  [ -n "$MEDIA_OVERRIDES" ] || return 1
  if [ -e "$COMPOSE_OVERRIDE_FILE" ] && ! managed_compose_override; then
    fail "compose.override.yml already exists and is not managed by BlueReel. It was not overwritten; merge approved roots deliberately."
  fi
  validate_registry
  mkdir -p -- "$LOCAL_CONFIGURATION_DIRECTORY"
  registry_candidate="$LOCAL_CONFIGURATION_DIRECTORY/.media-roots.tsv.tmp.$$"
  override_candidate="$REPOSITORY_ROOT/.compose.override.yml.tmp.$$"
  environment_candidate="$REPOSITORY_ROOT/.env.media-roots.tmp.$$"
  mounts_candidate="$LOCAL_CONFIGURATION_DIRECTORY/.media-root-mounts.tmp.$$"
  printf '%s\n' "$MEDIA_ROOT_REGISTRY_HEADER" > "$registry_candidate"
  : > "$mounts_candidate"

  configured_hosts=""
  media_root_paths=""
  definitions="["
  root_index=0
  existing_primary_host=""
  if [ -f "$MEDIA_ROOT_REGISTRY_FILE" ]; then
    existing_primary_host=$(awk -F '\t' '$1 == "primary" { print $4; exit }' "$MEDIA_ROOT_REGISTRY_FILE")
  fi
  while IFS= read -r supplied_path; do
    [ -n "$supplied_path" ] || continue
    resolved=$(canonical_media_path "$supplied_path")
    if [ -n "$existing_primary_host" ] && [ "$resolved" = "$existing_primary_host" ] && [ -n "$configured_hosts" ]; then
      fail "The registered primary media root must remain first so existing /media library paths stay stable. Omit it only for an explicit replacement."
    fi
    while IFS= read -r configured_host; do
      [ -n "$configured_host" ] || continue
      case "$resolved/" in "$configured_host/"*) fail "Approved media roots cannot contain one another.";; esac
      case "$configured_host/" in "$resolved/"*) fail "Approved media roots cannot contain one another.";; esac
    done <<EOF
$configured_hosts
EOF
    while IFS= read -r state_path; do
      [ -n "$state_path" ] || continue
      case "$resolved/" in "$state_path/"*) fail "An approved media root overlaps application runtime state.";; esac
      case "$state_path/" in "$resolved/"*) fail "An approved media root overlaps application runtime state.";; esac
    done <<EOF
$STATE_PATHS
EOF

    root_index=$((root_index + 1))
    prior_id=""
    prior_label=""
    prior_target=""
    if [ -f "$MEDIA_ROOT_REGISTRY_FILE" ]; then
      while IFS="$TAB" read -r registered_id registered_label registered_target registered_host; do
        [ "$registered_host" = "$resolved" ] || continue
        prior_id=$registered_id
        prior_label=$registered_label
        prior_target=$registered_target
        break
      done < "$MEDIA_ROOT_REGISTRY_FILE"
    fi
    if [ "$root_index" -eq 1 ]; then
      root_id=primary
      container_path=/media
    elif [ -n "$prior_id" ] && [ "$prior_id" != primary ]; then
      root_id=$prior_id
      container_path=$prior_target
    else
      root_id=$(new_media_root_id)
      container_path="/media-roots/$root_id"
    fi
    if [ -n "$prior_label" ]; then
      display_name=$prior_label
    else
      display_name=$(basename -- "$resolved")
      [ -n "$display_name" ] || display_name=Media
    fi
    if [ "${#display_name}" -gt 80 ] || printf '%s' "$display_name" | LC_ALL=C grep '[[:cntrl:]]' >/dev/null 2>&1; then
      fail "A media-root display name must be 1-80 printable characters."
    fi
    case "$display_name" in *'$'*) fail "Media-root display names cannot contain a dollar sign because Docker Compose interpolates that character.";; esac
    printf '%s\t%s\t%s\t%s\n' "$root_id" "$display_name" "$container_path" "$resolved" >> "$registry_candidate"
    configured_hosts="${configured_hosts}${configured_hosts:+
}$resolved"
    media_root_paths="${media_root_paths}${media_root_paths:+:}$container_path"
    escaped_id=$(json_escape "$root_id")
    escaped_label=$(json_escape "$display_name")
    escaped_container=$(json_escape "$container_path")
    [ "$root_index" -eq 1 ] || definitions="$definitions,"
    definitions="$definitions{\"id\":\"$escaped_id\",\"display_name\":\"$escaped_label\",\"path\":\"$escaped_container\"}"
    if [ "$root_index" -gt 1 ]; then
      printf '%s\t%s\n' "$resolved" "$container_path" >> "$mounts_candidate"
    fi
  done <<EOF
$MEDIA_OVERRIDES
EOF
  definitions="$definitions]"

  cp -- "$ENVIRONMENT_FILE" "$environment_candidate"
  chmod 600 "$environment_candidate"
  primary_host=$(awk -F '\t' 'NR == 2 { print $4; exit }' "$registry_candidate")
  replace_env_value MEDIA_PATH "$(dotenv_single_quote "$primary_host")" "$environment_candidate"
  replace_env_value MEDIA_ROOTS "$media_root_paths" "$environment_candidate"
  replace_env_value MEDIA_ROOT_DEFINITIONS "$(dotenv_single_quote "$definitions")" "$environment_candidate"

  has_extra_roots=0
  if [ -s "$mounts_candidate" ]; then
    has_extra_roots=1
    {
      printf '%s\n' "$GENERATED_OVERRIDE_MARKER"
      printf '%s\n' 'x-bluereel-generated:' '  version: 1' '  purpose: approved read-only media roots' 'services:'
      for service in backend worker; do
        printf '  %s:\n    volumes:\n' "$service"
        while IFS="$TAB" read -r host_path container_path; do
          quoted_host=$(yaml_single_quote "$host_path")
          quoted_container=$(yaml_single_quote "$container_path")
          printf '%s\n' '      - type: bind'
          printf "        source: '%s'\n" "$quoted_host"
          printf "        target: '%s'\n" "$quoted_container"
          printf '%s\n' '        read_only: true'
        done < "$mounts_candidate"
      done
    } > "$override_candidate"
  fi

  if [ "$has_extra_roots" -eq 1 ]; then
    docker compose --env-file "$environment_candidate" -f "$COMPOSE_FILE" -f "$override_candidate" config --quiet ||
      fail "Docker Compose rejected the proposed media-root configuration; existing local configuration was not changed."
  else
    docker compose --env-file "$environment_candidate" -f "$COMPOSE_FILE" config --quiet ||
      fail "Docker Compose rejected the proposed media-root configuration; existing local configuration was not changed."
  fi

  mv -- "$environment_candidate" "$ENVIRONMENT_FILE"
  mv -- "$registry_candidate" "$MEDIA_ROOT_REGISTRY_FILE"
  if [ "$has_extra_roots" -eq 1 ]; then
    mv -- "$override_candidate" "$COMPOSE_OVERRIDE_FILE"
  elif managed_compose_override; then
    rm -f -- "$COMPOSE_OVERRIDE_FILE"
  fi
  rm -f -- "$mounts_candidate" "$override_candidate"
  chmod 600 "$ENVIRONMENT_FILE" "$MEDIA_ROOT_REGISTRY_FILE"
  printf '%s\n' "Approved media roots were configured. Adding or changing roots requires controlled container recreation."
  while IFS="$TAB" read -r root_id display_name container_path host_path; do
    case "$root_id" in \#*|'') continue;; esac
    printf '  %s: %s -> %s (read-only)\n' "$display_name" "$host_path" "$container_path"
  done < "$MEDIA_ROOT_REGISTRY_FILE"
  return 0
}

CREATED_ENVIRONMENT=0
if [ -e "$ENVIRONMENT_FILE" ]; then
  [ -f "$ENVIRONMENT_FILE" ] || fail "$ENVIRONMENT_FILE exists but is not a regular file."
  printf '%s\n' "Keeping existing .env; it was not overwritten."
  if [ -n "$MEDIA_OVERRIDES" ] && [ "$CONFIGURE_MEDIA_ROOTS" -eq 0 ]; then
    fail "Existing media-root configuration was not changed. Rerun with --configure-media-roots and the intended --media-path values."
  fi
else
  [ -f "$ENVIRONMENT_EXAMPLE" ] || fail ".env.example is missing; refusing to invent an incomplete configuration."
  cp -- "$ENVIRONMENT_EXAMPLE" "$ENVIRONMENT_FILE"
  chmod 600 "$ENVIRONMENT_FILE"
  replace_env_value APP_SECRET_KEY "$(generate_secret)"
  replace_env_value PUID "$(id -u)"
  replace_env_value PGID "$(id -g)"
  CREATED_ENVIRONMENT=1
  printf '%s\n' "Created .env with a cryptographically secure application secret and this user's UID/GID."
fi

for key in APP_SECRET_KEY BIND_ADDRESS HTTP_PORT DATA_PATH DATABASE_PATH ARTWORK_PATH TEMP_PATH MEDIA_PATH BACKUP_PATH PUID PGID; do
  value=$(env_value "$key")
  [ -n "$value" ] || fail ".env is missing required setting $key. Compare it with .env.example; the script did not overwrite it."
done

APP_SECRET_KEY=$(env_value APP_SECRET_KEY)
[ "$APP_SECRET_KEY" != "GENERATE_WITH_BOOTSTRAP_DO_NOT_USE" ] || fail "APP_SECRET_KEY is still the example placeholder. Move .env aside and rerun, or replace it securely."
[ "${#APP_SECRET_KEY}" -ge 64 ] || fail "APP_SECRET_KEY must contain at least 64 characters of cryptographically random data."

BIND_ADDRESS=$(env_value BIND_ADDRESS)
case "$BIND_ADDRESS" in
  ::1) ;;
  *)
    printf '%s\n' "$BIND_ADDRESS" | awk -F. '
      NF != 4 { exit 1 }
      {
        for (i=1; i<=4; i++) {
          if ($i !~ /^[0-9]+$/ || $i < 0 || $i > 255) exit 1
        }
        if ($1 == 127 || $1 == 10 || ($1 == 172 && $2 >= 16 && $2 <= 31) ||
            ($1 == 192 && $2 == 168)) exit 0
        exit 1
      }
    ' || fail "BIND_ADDRESS must be loopback or an RFC1918 private address; wildcard and public binds are rejected."
    ;;
esac

HTTP_PORT=$(env_value HTTP_PORT)
case "$HTTP_PORT" in *[!0-9]*|'') fail "HTTP_PORT must be an integer from 1 through 65535.";; esac
[ "$HTTP_PORT" -ge 1 ] && [ "$HTTP_PORT" -le 65535 ] || fail "HTTP_PORT must be an integer from 1 through 65535."

PUID_VALUE=$(env_value PUID)
PGID_VALUE=$(env_value PGID)
case "$PUID_VALUE:$PGID_VALUE" in *[!0-9:]*|:*|*:) fail "PUID and PGID must be positive numeric container identities.";; esac
[ "$PUID_VALUE" -gt 0 ] && [ "$PGID_VALUE" -gt 0 ] || fail "PUID and PGID cannot be zero; running application containers as root is rejected."
[ "$PUID_VALUE" -eq "$(id -u)" ] || fail "PUID does not match the invoking user. Review the existing .env instead of changing directory ownership automatically."
[ "$PGID_VALUE" -eq "$(id -g)" ] || fail "PGID does not match the invoking user's primary group. Review the existing .env deliberately."

resolve_configured_path() {
  configured=$1
  case "$configured" in
    /*) absolute=$configured ;;
    *) absolute="$REPOSITORY_ROOT/$configured" ;;
  esac
  parent=$(dirname -- "$absolute")
  leaf=$(basename -- "$absolute")
  mkdir -p -- "$parent"
  parent=$(CDPATH= cd -- "$parent" && pwd -P)
  candidate="$parent/$leaf"
  if [ -d "$candidate" ]; then
    (CDPATH= cd -- "$candidate" && pwd -P)
  else
    printf '%s\n' "$candidate"
  fi
}

STATE_PATHS=""
for key in DATA_PATH DATABASE_PATH ARTWORK_PATH TEMP_PATH BACKUP_PATH; do
  configured=$(env_value "$key")
  resolved=$(resolve_configured_path "$configured")
  case "$resolved" in /|"$REPOSITORY_ROOT") fail "$key resolves to an unsafe broad directory: $resolved";; esac
  mkdir -p -- "$resolved"
  probe="$resolved/.application-write-test-$$"
  (umask 077 && printf test > "$probe") || fail "$key is not writable: $resolved"
  rm -f -- "$probe"
  if [ -n "$STATE_PATHS" ]; then
    while IFS= read -r existing_path; do
      [ -n "$existing_path" ] || continue
      case "$resolved/" in "$existing_path/"*) fail "Application state paths overlap; they must be isolated, not equal or nested.";; esac
      case "$existing_path/" in "$resolved/"*) fail "Application state paths overlap; they must be isolated, not equal or nested.";; esac
    done <<EOF
$STATE_PATHS
EOF
  fi
  STATE_PATHS="${STATE_PATHS}${STATE_PATHS:+
}$resolved"
done

if [ -z "$MEDIA_OVERRIDES" ] && [ "$SKIP_MEDIA_ROOTS" -eq 0 ] && { [ "$CREATED_ENVIRONMENT" -eq 1 ] || [ "$CONFIGURE_MEDIA_ROOTS" -eq 1 ]; }; then
  if interactive_input_available; then
    printf '%s\n' "Choose one or more host folders BlueReel may read. You may skip and configure them later."
    collect_interactive_media_roots
  elif [ "$CONFIGURE_MEDIA_ROOTS" -eq 1 ]; then
    fail "No media roots were supplied in a non-interactive session. Pass --media-path or omit --configure-media-roots."
  fi
fi

MEDIA_CONFIGURATION_CHANGED=0
if [ -n "$MEDIA_OVERRIDES" ]; then
  configure_media_roots
  MEDIA_CONFIGURATION_CHANGED=1
fi

MEDIA_CONFIGURED=$(env_value MEDIA_PATH)
MEDIA_RESOLVED=$(resolve_configured_path "$MEDIA_CONFIGURED")
if [ ! -d "$MEDIA_RESOLVED" ]; then
  if [ "$CREATED_ENVIRONMENT" -eq 1 ] && [ "$MEDIA_CONFIGURED" = "./media" ]; then
    mkdir -p -- "$MEDIA_RESOLVED"
    printf 'Created the default empty media directory at %s.\n' "$MEDIA_RESOLVED"
  else
    fail "MEDIA_PATH does not exist or is not a directory: $MEDIA_RESOLVED"
  fi
fi
[ -r "$MEDIA_RESOLVED" ] && [ -x "$MEDIA_RESOLVED" ] || fail "MEDIA_PATH is not readable/traversable by the current user: $MEDIA_RESOLVED"

validate_registry
REGISTERED_ROOT_COUNT=0
if [ -f "$MEDIA_ROOT_REGISTRY_FILE" ]; then
  while IFS="$TAB" read -r root_id display_name container_path host_path; do
    case "$root_id" in \#*|'') continue;; esac
    REGISTERED_ROOT_COUNT=$((REGISTERED_ROOT_COUNT + 1))
    canonical_registered=$(canonical_media_path "$host_path")
    [ "$canonical_registered" = "$host_path" ] || fail "A configured media root no longer resolves to its registered canonical path. Reconfigure roots deliberately."
    printf '%s\n' "$STATE_PATHS" | while IFS= read -r state_path; do
      [ -n "$state_path" ] || continue
      case "$host_path/" in "$state_path/"*) fail "A configured media root overlaps application runtime state.";; esac
      case "$state_path/" in "$host_path/"*) fail "A configured media root overlaps application runtime state.";; esac
    done
  done < "$MEDIA_ROOT_REGISTRY_FILE"
fi
if [ "$REGISTERED_ROOT_COUNT" -gt 1 ] && ! managed_compose_override; then
  fail "Multiple approved media roots are registered, but their managed Compose override is missing or unrecognized."
fi

printf '%s\n' "$STATE_PATHS" | while IFS= read -r state_path; do
  [ -n "$state_path" ] || continue
  case "$state_path/" in "$MEDIA_RESOLVED/"*) fail "A runtime state path is inside MEDIA_PATH; source media must remain isolated and read-only.";; esac
  case "$MEDIA_RESOLVED/" in "$state_path/"*) fail "MEDIA_PATH is inside a runtime state path; choose isolated directories.";; esac
done

cd -- "$REPOSITORY_ROOT"
docker compose --env-file "$ENVIRONMENT_FILE" config --quiet

if [ "$NO_START" -eq 1 ]; then
  if [ "$MEDIA_CONFIGURATION_CHANGED" -eq 1 ]; then
    printf '%s\n' "Configuration and paths are valid. Services were not started because --no-start was supplied. Re-run without --no-start to recreate the affected containers safely."
  else
    printf '%s\n' "Configuration and paths are valid. Services were not started because --no-start was supplied."
  fi
  exit 0
fi

if [ "$NO_BUILD" -eq 1 ]; then
  docker compose --env-file "$ENVIRONMENT_FILE" up --detach
else
  docker compose --env-file "$ENVIRONMENT_FILE" up --detach --build
fi

case "$BIND_ADDRESS" in 127.*|::1) DISPLAY_HOST=localhost;; *) DISPLAY_HOST=$BIND_ADDRESS;; esac
LOCAL_URL="http://$DISPLAY_HOST:$HTTP_PORT"
HEALTH_URL="$LOCAL_URL/api/v1/health/ready"

attempt=1
healthy=0
while [ "$attempt" -le 60 ]; do
  if command -v curl >/dev/null 2>&1; then
    if curl --fail --silent --show-error --max-time 3 "$HEALTH_URL" >/dev/null 2>&1; then healthy=1; break; fi
  elif command -v wget >/dev/null 2>&1; then
    if wget --quiet --timeout=3 --output-document=/dev/null "$HEALTH_URL"; then healthy=1; break; fi
  else
    fail "Services started, but curl or wget is required to run the host health check. Visit $HEALTH_URL manually."
  fi
  sleep 2
  attempt=$((attempt + 1))
done

[ "$healthy" -eq 1 ] || fail "Services started but readiness did not succeed within 120 seconds. Inspect with: docker compose logs"

printf '%s is ready at %s\n' "$PRODUCT_NAME" "$LOCAL_URL"
printf '%s\n' "Complete Owner setup in the browser. No public firewall or router settings were changed."
